#include "Character.h"




int Character::getX()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -87--2--83-1--49637181:162d9d520f1:-8000:0000000000000BD9 begin
{
    return 0;
}
// section -87--2--83-1--49637181:162d9d520f1:-8000:0000000000000BD9 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Character::getY()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -87--2--83-1--49637181:162d9d520f1:-8000:0000000000000C02 begin
{
    return 0;
}
// section -87--2--83-1--49637181:162d9d520f1:-8000:0000000000000C02 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
