#include "Enemy.h"




int Enemy::newOperation()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -87--2--83-1-2f82c4ae:162dec31678:-8000:0000000000000B5A begin
{
    return 0;
}
// section -87--2--83-1-2f82c4ae:162dec31678:-8000:0000000000000B5A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
